services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: isg-pms-backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    environment:
      DB_SERVER: host.docker.internal\\SQLEXPRESS
      DB_NAME: jam

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: isg-pms-frontend

    ports:
      - "3000:3000"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend